baseURL = 'https://concon.ca/blog'
languageCode = 'en-us'
title = "conconclusions blog"
relativeURLs = true

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "blogposts"
    url = "/blogposts/"
    weight = 2
  [[menu.main]]
    name = "tags"
    url = "/tags/"
    weight = 3

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "my thoughts."